-- Autogenerated lua file by the Shanker tool
-- 'Wimps and posers -- leave the hall! -- ManOwaR
--
-- DO NOT HAND EDIT.
--
dependents =
{
}
text_styles =
{
    default =
    {
        color =
        {
            0.72156862745098,
            0.525490196078431,
            0.0431372549019608,
            1,
        },
        font = [[arialbd.ttf]],
        size = 18,
        dpi = 72,
        chars = [[ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789 ><{}[].,:;!@#$%^?()&*\/-"|]],
    },
}
skins =
{
}
widgets =
{
    {
        name = [[bg]],
        isVisible = true,
        x = 0.5,
        y = 0.5,
        w = 1,
        h = 1,
        ctor = [[image]],
        color =
        {
            1,
            1,
            1,
            1,
        },
        images =
        {
            {
                file = [[splash.png]],
            },
        },
    },
    {
        name = [[hs0]],
        isVisible = true,
        x = 0.2404939,
        y = 0.1646532,
        w = 0.4,
        h = 0.2,
        ctor = [[label]],
        halign = MOAITextBox.LEFT_JUSTIFY,
        valign = MOAITextBox.LEFT_JUSTIFY,
        text_style = [[default]],
        padleft = 0,
        padright = 0,
        str = [[High score]],
    },
}
properties =
{
    sinksInput = false,
}
return { dependents = dependents, text_styles = text_styles, skins = skins, widgets = widgets, properties = properties }
