
return
{
	UNIT_PLAYER = 0,
	UNIT_SCOUT = 1,
	UNIT_FIGHTER = 2,
	UNIT_GUARDTOWER = 3,
	UNIT_WATCHTOWER = 4,
	UNIT_TOWER_SCOUT = 5,
	UNIT_MERC = 10,
	UNIT_MERC2 = 11,
	UNIT_MERC3 = 12,

	EV_UNIT_ARRIVED = 1,
	EV_UNIT_LEFT = 2,

	EV_PHASEIN = 99,
	EV_UPDATE_RESOURCES = 100,
}
