-- Autogenerated lua file by the Shanker tool
-- 'Wimps and posers -- leave the hall! -- ManOwaR
--
-- DO NOT HAND EDIT.
--
dependents =
{
}
text_styles =
{
    default =
    {
        color =
        {
            0.862745098039216,
            0.862745098039216,
            0.862745098039216,
            1,
        },
        font = [[arialbd.ttf]],
        size = 14,
        dpi = 72,
        chars = [[ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789 ><{}[].,:;!@#$%^?()&*\/-"|]],
    },
    bigred =
    {
        color =
        {
            0.698039215686274,
            0.133333333333333,
            0.133333333333333,
            1,
        },
        font = [[arialbd.ttf]],
        size = 26,
        dpi = 72,
        chars = [[ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789 ><{}[].,:;!@#$%^?()&*\/-"|]],
    },
    detail =
    {
        color =
        {
            0.862745098039216,
            0.862745098039216,
            0.862745098039216,
            1,
        },
        font = [[arialbd.ttf]],
        size = 12,
        dpi = 72,
        chars = [[ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789 ><{}[].,:;!@#$%^?()&*\/-"|]],
    },
    hotkey =
    {
        color =
        {
            1,
            0.549019607843137,
            0,
            1,
        },
        font = [[arialbd.ttf]],
        size = 14,
        dpi = 72,
        chars = [[ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789 ><{}[].,:;!@#$%^?()&*\/-"|]],
    },
    red =
    {
        color =
        {
            1,
            0,
            0,
            1,
        },
        font = [[arialbd.ttf]],
        size = 14,
        dpi = 72,
        chars = [[ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789 ><{}[].,:;!@#$%^?()&*\/-"|]],
    },
    orange =
    {
        color =
        {
            1,
            0.647058823529412,
            0,
            1,
        },
        font = [[arialbd.ttf]],
        size = 14,
        dpi = 72,
        chars = [[ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789 ><{}[].,:;!@#$%^?()&*\/-"|]],
    },
}
skins =
{
    {
        name = [[Unit]],
        isVisible = true,
        x = 0,
        y = 0,
        w = 0.09999999,
        h = 0.08353446,
        ctor = [[group]],
        children =
        {
            {
                name = [[selectImg]],
                isVisible = true,
                x = 0,
                y = 0,
                w = 0.032,
                h = 0.045,
                ctor = [[image]],
                color =
                {
                    0.345098039215686,
                    0.345098039215686,
                    0.345098039215686,
                    0.635294117647059,
                },
                images =
                {
                    {
                        file = [[select.png]],
                    },
                },
            },
            {
                name = [[unitBtn]],
                isVisible = true,
                x = 0,
                y = 0,
                w = 0.03,
                h = 0.04,
                ctor = [[button]],
                str = [[Button]],
                halign = MOAITextBox.CENTER_JUSTIFY,
                valign = MOAITextBox.CENTER_JUSTIFY,
                text_style = [[]],
                padleft = 0,
                padright = 0,
                images =
                {
                    {
                        file = [[unit_scout.png]],
                    },
                    {
                        file = [[unit_scout.png]],
                    },
                    {
                        file = [[unit_scout.png]],
                    },
                },
            },
            {
                name = [[unitName]],
                isVisible = true,
                x = 1.490116E-08,
                y = -0.03603446,
                w = 0.1,
                h = 0.05,
                ctor = [[label]],
                halign = MOAITextBox.CENTER_JUSTIFY,
                valign = MOAITextBox.LEFT_JUSTIFY,
                text_style = [[detail]],
                padleft = 0,
                padright = 0,
                str = [[Name]],
            },
        },
    },
    {
        name = [[AwayUnit]],
        isVisible = true,
        x = 0,
        y = 0,
        w = 0.09999999,
        h = 0.08353446,
        ctor = [[group]],
        children =
        {
            {
                name = [[awaySelectImg]],
                isVisible = true,
                x = 0,
                y = 0.02001724,
                w = 0.032,
                h = 0.045,
                ctor = [[image]],
                color =
                {
                    0.345098039215686,
                    0.345098039215686,
                    0.345098039215686,
                    0.635294117647059,
                },
                images =
                {
                    {
                        file = [[select.png]],
                    },
                },
            },
            {
                name = [[awayUnitBtn]],
                isVisible = true,
                x = 0,
                y = 0.02001724,
                w = 0.03,
                h = 0.04,
                ctor = [[button]],
                str = [[Button]],
                halign = MOAITextBox.CENTER_JUSTIFY,
                valign = MOAITextBox.CENTER_JUSTIFY,
                text_style = [[]],
                padleft = 0,
                padright = 0,
                images =
                {
                    {
                        file = [[unit_scout.png]],
                    },
                    {
                        file = [[unit_scout.png]],
                    },
                    {
                        file = [[unit_scout.png]],
                    },
                },
            },
            {
                name = [[awayUnitName]],
                isVisible = true,
                x = 1.490116E-08,
                y = -0.01601723,
                w = 0.1,
                h = 0.05,
                ctor = [[label]],
                halign = MOAITextBox.CENTER_JUSTIFY,
                valign = MOAITextBox.LEFT_JUSTIFY,
                text_style = [[detail]],
                padleft = 0,
                padright = 0,
                str = [[Name]],
            },
        },
    },
}
widgets =
{
    {
        name = [[timeLabel]],
        isVisible = true,
        x = 0.2351724,
        y = 0.9386207,
        w = 0.4,
        h = 0.05,
        ctor = [[label]],
        halign = MOAITextBox.LEFT_JUSTIFY,
        valign = MOAITextBox.LEFT_JUSTIFY,
        text_style = [[default]],
        padleft = 0,
        padright = 0,
        str = [[Time: 0:00]],
    },
    {
        name = [[tooltipTxt]],
        isVisible = true,
        x = 0.2213793,
        y = 1.116552,
        w = 0.4,
        h = 0.2,
        ctor = [[label]],
        halign = MOAITextBox.LEFT_JUSTIFY,
        valign = MOAITextBox.LEFT_JUSTIFY,
        text_style = [[default]],
        padleft = 0,
        padright = 0,
        str = [[TOOLTIP]],
    },
    {
        name = [[infoLabel]],
        isVisible = true,
        x = 0.8384627,
        y = 0.9052586,
        w = 0.3,
        h = 0.1,
        ctor = [[label]],
        halign = MOAITextBox.LEFT_JUSTIFY,
        valign = MOAITextBox.LEFT_JUSTIFY,
        text_style = [[bigred]],
        padleft = 0,
        padright = 0,
        str = [[]],
    },
    {
        name = [[buy1Btn]],
        isVisible = false,
        x = 0.07928157,
        y = 0.7331681,
        w = 0.1,
        h = 0.06,
        ctor = [[button]],
        str = [[Buy Fighter]],
        halign = MOAITextBox.CENTER_JUSTIFY,
        valign = MOAITextBox.CENTER_JUSTIFY,
        text_style = [[detail]],
        padleft = 0,
        padright = 0,
        images =
        {
            {
                file = [[dkgrey.png]],
            },
            {
                file = [[dkgrey.png]],
            },
            {
                file = [[dkgrey.png]],
            },
        },
    },
    {
        name = [[buy0Btn]],
        isVisible = false,
        x = 0.07793099,
        y = 0.8066379,
        w = 0.1,
        h = 0.06,
        ctor = [[button]],
        str = [[Buy Scout]],
        hotkey = string.byte('s'),
        halign = MOAITextBox.CENTER_JUSTIFY,
        valign = MOAITextBox.CENTER_JUSTIFY,
        text_style = [[detail]],
        padleft = 0,
        padright = 0,
        images =
        {
            {
                file = [[dkgrey.png]],
            },
            {
                file = [[dkgrey.png]],
            },
            {
                file = [[dkgrey.png]],
            },
        },
    },
    {
        name = [[buy2Btn]],
        isVisible = false,
        x = 0.08081885,
        y = 0.6593788,
        w = 0.1,
        h = 0.06,
        ctor = [[button]],
        str = [[Buy Captain]],
        halign = MOAITextBox.CENTER_JUSTIFY,
        valign = MOAITextBox.CENTER_JUSTIFY,
        text_style = [[detail]],
        padleft = 0,
        padright = 0,
        images =
        {
            {
                file = [[dkgrey.png]],
            },
            {
                file = [[dkgrey.png]],
            },
            {
                file = [[dkgrey.png]],
            },
        },
    },
    {
        name = [[buy3Btn]],
        isVisible = false,
        x = 0.07928157,
        y = 0.5902012,
        w = 0.1,
        h = 0.06,
        ctor = [[button]],
        str = [[Buy General]],
        halign = MOAITextBox.CENTER_JUSTIFY,
        valign = MOAITextBox.CENTER_JUSTIFY,
        text_style = [[detail]],
        padleft = 0,
        padright = 0,
        images =
        {
            {
                file = [[dkgrey.png]],
            },
            {
                file = [[dkgrey.png]],
            },
            {
                file = [[dkgrey.png]],
            },
        },
    },
    {
        name = [[resourcesLabel]],
        isVisible = true,
        x = 0.2338218,
        y = 0.8765517,
        w = 0.4,
        h = 0.05,
        ctor = [[label]],
        halign = MOAITextBox.LEFT_JUSTIFY,
        valign = MOAITextBox.LEFT_JUSTIFY,
        text_style = [[default]],
        padleft = 0,
        padright = 0,
        str = [[Credits: 0]],
    },
    {
        name = [[enemyLabel]],
        isVisible = true,
        x = 0.4060919,
        y = 0.9052586,
        w = 0.3,
        h = 0.1,
        ctor = [[label]],
        halign = MOAITextBox.LEFT_JUSTIFY,
        valign = MOAITextBox.LEFT_JUSTIFY,
        text_style = [[bigred]],
        padleft = 0,
        padright = 0,
        str = [[Enemy Detected]],
    },
}
properties =
{
    sinksInput = false,
}
return { dependents = dependents, text_styles = text_styles, skins = skins, widgets = widgets, properties = properties }
